#!/bin/bash
export SSH_AUTH_SOCK=$(find /tmp/ssh-* -user `whoami` -name 'agent*' -printf '%T@ %p\n' 2>/dev/null | sort -k 1nr | sed 's/^[^ ]* //' | head -n 1)
if ssh-add -l 2>&1 > /dev/null; then
  echo Found working SSH Agent:
  ssh-add -l
  return
fi
echo Cannot find ssh agent -- reconnect with ssh -A
